services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db_data_Myapi:/var/lib/postgresql/data/pgdata

  docfx:
    build:
      context: .
      dockerfile: Dockerfile.docfx
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ["docfx", "docfx.json", "--serve", "--hostname", "0.0.0.0", "--port", "8080"]

volumes:
  db_data_Myapi: